### ISSUE TITLE
bug: Deno error after existing workspace error

### ISSUE THREAD

**Issue by HurricanKai** [windmill-labs/windmill#1179]
### Describe the bug

When attempting to create an already existing workspace def in the CLI Deno errors

Log:
```
! Workspace name already exists
error: Uncaught Error: Deno.core.runMicrotasks() is not supported in this environment
      throw new Error(
            ^
    at Object.runMicrotasks (https://deno.land/std@0.170.0/node/_core.ts:22:13)
    at processTicksAndRejections (https://deno.land/std@0.170.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.170.0/node/process.ts:375:7
    at innerInvokeEventListeners (deno:ext/web/02_event.js:776:9)
    at invokeEventListeners (deno:ext/web/02_event.js:816:7)
    at dispatch (deno:ext/web/02_event.js:685:11)
    at dispatchEvent (deno:ext/web/02_event.js:1066:14)
    at [deno:cli/worker.rs:90:39]:1:1
```

### To reproduce

1. Create a workspace using `wmill workspace add`
2. Attempt to create the same workspace again
3. Notice `! Workspace name already exists` (this is expected)
4. Notice Deno internal error

### Expected behavior

No Deno error is printed and the CLI exists "gracefully" (the "error" about the existing workspace is expected)

### Additional Context

This appears to be a regression in either deno or our code.

**Comment by HurricanKai** [comment]
I have recently updated my local deno version, and have never seen this error, so I'm considering it a possibility that this is a deno regression, although that is very unlikely in general.
Local deno version: 1.30.0.
CLI version is on top of #1071

**Comment by HurricanKai** [comment]
Not related to the workspace add command. Can happen pretty much on any (?) command.

**Comment by HurricanKai** [comment]
Looks like this is a bug somewhere in the windmill API deno client. Minimal Repo:
```ts
import * as wmill from "https://deno.land/x/windmill@v1.62.0/mod.ts";

wmill.setClient(
  "<token>",
  "https://app.windmill.dev",
);
await wmill.SettingsService.backendVersion();
```
(any API call will do, but has to succeed)
causes:
```
error: Uncaught Error: Deno.core.runMicrotasks() is not supported in this environment
      throw new Error(
            ^
    at Object.runMicrotasks (https://deno.land/std@0.170.0/node/_core.ts:22:13)
    at processTicksAndRejections (https://deno.land/std@0.170.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.170.0/node/process.ts:375:7
    at innerInvokeEventListeners (deno:ext/web/02_event.js:776:9)
    at invokeEventListeners (deno:ext/web/02_event.js:816:7)
    at dispatch (deno:ext/web/02_event.js:685:11)
    at dispatchEvent (deno:ext/web/02_event.js:1066:14)
    at [deno:cli/worker.rs:90:39]:1:1
```

**Comment by HurricanKai** [comment]
Can't reproduce outside of specific local environment. If you come here because you've encountered the same problem, please comment here & the issue will be reopened.

**Comment by HurricanKai** [comment]
It turns out it's actually a cache issue. Delete your deno cache and things should go back to working normally. (Deno cache found using `deno info`)
