### ISSUE TITLE
bug: ModuleNotFound for Python script

### ISSUE THREAD

**Issue by evoxmusic** [windmill-labs/windmill#1909]
### Describe the bug

Hi 👋🏽 , first of all, thanks for all the great work. 

I'm creating a python script and I want to import the `qovery` module (available on pip) and I got the following error when executing the script.

```
ob 01896f8c-f9cd-b596-a1e5-f6dec6dc5465 on worker wk-fjr54-oPHKg

resolving dependencies...
content of requirements:
dependency
qovery@git+https://github.com/Qovery/qovery-client-python@c9c44af
wmill==1.133.0

found cached resolution: py-4b21f7d4b49306902063b7059382605144f8524fa89b0fa521154d5d8b17ba0b
--- PIP INSTALL ---

anyio==3.7.1 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting anyio==3.7.1
  Downloading anyio-3.7.1-py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.9/80.9 kB 2.3 MB/s eta 0:00:00
Installing collected packages: anyio
Successfully installed anyio-3.7.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

attrs==23.1.0 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting attrs==23.1.0
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 3.2 MB/s eta 0:00:00
Installing collected packages: attrs
Successfully installed attrs-23.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

certifi==2023.5.7 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting certifi==2023.5.7
  Downloading certifi-2023.5.7-py3-none-any.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.0/157.0 kB 4.7 MB/s eta 0:00:00
Installing collected packages: certifi
Successfully installed certifi-2023.5.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

h11==0.14.0 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting h11==0.14.0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 1.5 MB/s eta 0:00:00
Installing collected packages: h11
Successfully installed h11-0.14.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

httpcore==0.16.3 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting httpcore==0.16.3
  Downloading httpcore-0.16.3-py3-none-any.whl (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 kB 3.1 MB/s eta 0:00:00
Installing collected packages: httpcore
Successfully installed httpcore-0.16.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

httpx==0.23.3 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting httpx==0.23.3
  Downloading httpx-0.23.3-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 6.7 MB/s eta 0:00:00
Installing collected packages: httpx
Successfully installed httpx-0.23.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

idna==3.4 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting idna==3.4
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 3.2 MB/s eta 0:00:00
Installing collected packages: idna
Successfully installed idna-3.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

rfc3986[idna2008]==1.5.0 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting rfc3986[idna2008]==1.5.0
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Installing collected packages: rfc3986
Successfully installed rfc3986-1.5.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

sniffio==1.3.0 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting sniffio==1.3.0
  Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
Installing collected packages: sniffio
Successfully installed sniffio-1.3.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

windmill-api==1.133.0 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting windmill-api==1.133.0
  Downloading windmill_api-1.133.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 16.7 MB/s eta 0:00:00
Installing collected packages: windmill-api
Successfully installed windmill-api-1.133.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
--- PIP INSTALL ---

wmill==1.133.0 is being installed for the first time.
 It will be cached for all ulterior uses.
Collecting wmill==1.133.0
  Downloading wmill-1.133.0-py3-none-any.whl (4.6 kB)
Installing collected packages: wmill
Successfully installed wmill-1.133.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

--- PYTHON CODE EXECUTION ---

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/windmill/wk-fjr54-oPHKg/01896f8c-f9cd-b596-a1e5-f6dec6dc5465/wrapper.py", line 8, in <module>
    from u.rphilogene import playground_accounts_clean_up as inner_script
  File "/tmp/windmill/wk-fjr54-oPHKg/01896f8c-f9cd-b596-a1e5-f6dec6dc5465/u/rphilogene/playground_accounts_clean_up.py", line 5, in <module>
    import qovery
ModuleNotFoundError: No module named 'qovery'
```

My script looks like this:

```python
import os
import wmill
import time
import logging
import qovery
from qovery.api import members_api

#requirements:
#dependency
#qovery@git+https://github.com/Qovery/qovery-client-python@c9c44af
#wmill==1.133.0

def retry(func):
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as e:
            logging.error(e)
            logging.warning("Waiting 1 second and retrying...")
            time.sleep(1)
            return func(*args, **kwargs)

    return wrapper

def list_members(qovery_client, organization_id):
    try:
        return members_api.MembersApi(qovery_client).get_organization_members(organization_id).results
    except qovery.exceptions.ApiException as e:
        if e.status == 429:
            logging.warning("Too many requests to Qovery API...")
            return retry(list_members)(qovery_client, organization_id)
        raise e

def main(
    playground_organization_id: str = wmill.get_variable("f/Product/QOVERY_X_ORGANIZATION_ID"),
    qovery_api_access_token: str = wmill.get_variable("f/Product/QOVERY_X_ACCESS_TOKEN")
):
    configuration = qovery.Configuration(access_token=qovery_api_access_token)
    qovery_client = qovery.ApiClient(configuration)
```

So nothing fancy. 

### To reproduce

Import qovery module into a python script. My qovery module is defined like this

```
import os
import wmill
import time
import logging
import qovery
from qovery.api import members_api

#requirements:
#dependency
#qovery@git+https://github.com/Qovery/qovery-client-python@c9c44af
#wmill==1.133.0
```

### Expected behavior

I expect to see my python script executed well without a qovery module error

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/1284743/8498954a-0263-45ad-bb5f-c247544b7ce2)

### Browser information

Firefox

### Application version

Windmill CE v1.133.0

**Comment by rubenfiszel** [comment]
Fixed on latest

**Comment by evoxmusic** [comment]
that was fast - thank you @rubenfiszel - I'll try this out today. Thx
