### ISSUE TITLE
bug: referenced script imports fail in Slack flow

### ISSUE THREAD

**Issue by mattiaseyram** [windmill-labs/windmill#2015]
### Describe the bug

Attempted to test nested scripts and flows for Windmill's slack integration on Windmill Cloud.

Running the test flow I created via the windmill async/sync webhooks work as intended, but with the slack handler the script fails with the following message:

```
Error message: ExitCode: 1, last log lines:
Not found: Script not found at name f/sample/sample_script_1_py 404
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/wrapper.py", line 8, in <module>
    from f.sample import sample_script_2_py as inner_script
  File "/tmp/f/sample/sample_script_2_py.py", line 1, in <module>
    from f.sample.sample_script_1_py import hello_world
  File "/tmp/loader.py", line 48, in find_spec
    raise ImportError(f"Script {script_path} not found")
ImportError: Script f/sample/sample_script_1_py not found
```

### To reproduce

1. Create a python or TS script (sample_script_1) exporting a function
2. Create a python or TS script (sample_script_2) importing said function
3. Create an internal flow (sample_flow) that calls sample_script_2
4. Create a flow (slack_bot) following windmill's slack bot documentation
5. Call the internal flow (sample_flow) inside the slack_bot flow
6. Trigger slack_bot flow via API and slack /windmill command

### Expected behavior

input
```
/windmill sample py me
```

output
```
Hello from PY me!
``` 

### Screenshots

Slack bot script
<img width="830" alt="image" src="https://github.com/windmill-labs/windmill/assets/12214004/c85b5204-ad6b-437d-98c7-b984af74b0c1">

Internal Flow
<img width="832" alt="image" src="https://github.com/windmill-labs/windmill/assets/12214004/af1c3d99-19d2-44ae-aa49-a53f03499d65">

sample_script_1_py
```py
def hello_world(name: str):
    return f"Hello from PY {name}!"
```

sample_script_2_py
```py
from f.sample.sample_script_1_py import hello_world


def main(name: str):
    return hello_world(name)
```

slack_bot flow
```json
{
    "modules": [
        {
            "id": "n",
            "value": {
                "lock": "",
                "type": "rawscript",
                "content": "// import * as wmill from \"https://deno.land/x/windmill@v1.142.0/mod.ts\"\n\ntype Payload = {\n  type: \"sample\";\n  input: string;\n  isTS: boolean;\n} | {\n  type: \"default\";\n  input: string;\n};\n\nexport async function main(input: string): Promise<Payload> {\n  if (input.trim().toLowerCase().startsWith(\"sample\")) {\n    input = input.substring(\"sample\".length).trim();\n    let isTS = false;\n\n    if (input.toLowerCase().startsWith(\"ts\")) {\n      input = input.substring(\"ts\".length).trim();\n      isTS = true;\n    } else if (\n      input.toLowerCase().startsWith(\"py\")\n    ) {\n      input = input.substring(\"py\".length).trim();\n      isTS = false;\n    }\n\n    return {\n      type: \"sample\",\n      input,\n      isTS,\n    };\n  }\n\n  return {\n    type: \"default\",\n    input,\n  };\n}\n",
                "language": "deno",
                "input_transforms": {
                    "input": {
                        "expr": "`${flow_input.text}`",
                        "type": "javascript"
                    }
                }
            }
        },
        {
            "id": "h",
            "value": {
                "type": "branchone",
                "default": [
                    {
                        "id": "k",
                        "value": {
                            "lock": "",
                            "type": "rawscript",
                            "content": "// import * as wmill from \"https://deno.land/x/windmill@v1.142.0/mod.ts\"\n\nexport async function main() {\n  throw new Error(\"unknownCommand\");\n}\n",
                            "language": "deno",
                            "input_transforms": {}
                        }
                    }
                ],
                "branches": [
                    {
                        "expr": "results.n.type === 'sample'",
                        "modules": [
                            {
                                "id": "j",
                                "value": {
                                    "path": "f/sample/sample_flow",
                                    "type": "flow",
                                    "input_transforms": {
                                        "text": {
                                            "expr": "`${results.n.input}`",
                                            "type": "javascript"
                                        },
                                        "is_ts": {
                                            "expr": "results.n.isTS",
                                            "type": "javascript"
                                        }
                                    }
                                }
                            }
                        ],
                        "summary": ""
                    }
                ]
            },
            "summary": ""
        },
        {
            "id": "m",
            "value": {
                "lock": "",
                "type": "rawscript",
                "content": "export async function main(response_url: string, output: string) {\n  if (response_url) {\n    await fetch(response_url, {\n      method: \"POST\",\n      body: JSON.stringify({ text: output }),\n    });\n  }\n\n  return output;\n}\n",
                "language": "deno",
                "input_transforms": {
                    "output": {
                        "expr": "`${results.h}`",
                        "type": "javascript"
                    },
                    "response_url": {
                        "expr": "`${flow_input.response_url}`",
                        "type": "javascript"
                    }
                }
            }
        }
    ],
    "same_worker": true,
    "failure_module": {
        "id": "failure",
        "value": {
            "type": "rawscript",
            "content": "// import * as wmill from \"https://deno.land/x/windmill@v1.142.0/mod.ts\"\n\nexport async function main(\n  response_url: string,\n  input: string,\n  errorMessage: string,\n) {\n  const output =\n    `Learning Platform Slack Bot https://app.windmill.dev/flows/get/f/slack_bot/slack_bot?workspace=learning-platform\n  \n${\n      errorMessage === \"unknownCommand\"\n        ? (\n          `Unknown command: ${input}`\n        )\n        : (\n          `Error message: ${errorMessage}`\n        )\n    }\n\nUsage:\n1. sample {ts|py|empty} hello {text}`;\n\n  if (response_url) {\n    await fetch(response_url, {\n      method: \"POST\",\n      body: JSON.stringify({ text: output }),\n    });\n  }\n\n  return output;\n}\n",
            "language": "deno",
            "input_transforms": {
                "input": {
                    "expr": "`${flow_input.text}`",
                    "type": "javascript"
                },
                "errorMessage": {
                    "expr": "`${error.message}`",
                    "type": "javascript"
                },
                "response_url": {
                    "expr": "`${flow_input.response_url}`",
                    "type": "javascript"
                }
            }
        }
    }
}
```

**Comment by mattiaseyram** [comment]
Closing issue, thank you @rubenfiszel!

Needed to apply the slack group permissions to the sample folder where the scripts lived.
