### ISSUE TITLE
bug: "this.socket?.destroy is not a function" when npm:got encounters 404

### ISSUE THREAD

**Issue by some-user123** [windmill-labs/windmill#2113]
### Describe the bug

Test script:
```ts
import got from "npm:got@13.0.0";

export async function main() {
  const res = await got.get("https://httpstat.us/404")
}

main()
```

When used locally with `deno run ...` as expected:
```
error: Uncaught (in promise) HTTPError: Response code 404 (Not Found)  
...
```

However, when run in windmill:
```
TypeError: this.socket?.destroy is not a function
    at HttpsClientRequest.destroy (node:http:523:22)
    at Request._destroy (file:///tmp/windmill/cache/deno/npm/registry.npmjs.org/got/13.0.0/dist/source/core/index.js:478:27)
    at _destroy (ext:deno_node/_stream.mjs:1538:15)
    at Request.destroy (ext:deno_node/_stream.mjs:1508:9)
    at Request._error (file:///tmp/windmill/cache/deno/npm/registry.npmjs.org/got/13.0.0/dist/source/core/index.js:1013:14)
    at file:///tmp/windmill/cache/deno/npm/registry.npmjs.org/got/13.0.0/dist/source/core/index.js:401:23
    at Object.runMicrotasks (ext:core/01_core.js:836:30)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:53:14)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:5)
    at eventLoopTick (ext:core/01_core.js:189:21)
```

### To reproduce

Create new deno script with above code & execute.

### Expected behavior

Deno in windmill should show the same behavior as `deno run...`.

### Application version

CE v1.149.0-8-g067908c0

### Additional Context

```
$ deno --version
deno 1.36.1 (release, x86_64-pc-windows-msvc)
v8 11.6.189.12
typescript 5.1.6
```

**Comment by rubenfiszel** [comment]
fixed on latest
