### ISSUE TITLE
bug: python library `wmill` pins an older version of `httpx` which conflicts with other deps

### ISSUE THREAD

**Issue by JokerQyou** [windmill-labs/windmill#2827]
### Describe the bug

This is similar to #2220, it's just with different dependencies. I have a library that requires `httpx<0.26,>=0.25`, but `wmill==1.223.1` requires `httpx~=0.24.1`.

Run log:

```
job 018c5361-486d-cc6f-829c-137c844338cf on worker wk-default-1d3a11bd4acf-K2j1q (tag: python3)

resolving dependencies...
content of requirements:
bilibili-api-python==16.1.1
wmill==1.223.1

  ERROR: Cannot install -r requirements.in (line 1) and -r requirements.in (line 2) because these package versions have conflicting dependencies.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 439, in resolve
    raise ResolutionImpossible(self.state.backtrack_causes)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('httpx~=0.24.1'), parent=LinkCandidate('https://files.pythonhosted.org/packages/ea/c8/5847f15723f427f6f704c71947a607d6ede04773cfe282d863d2a1b13f1b/bilibili_api_python-16.1.1-py3-none-any.whl (from https://pypi.org/simple/bilibili-api-python/) (requires-python:>=3.8)')), RequirementInformation(requirement=SpecifierRequirement('httpx<0.26,>=0.25'), parent=LinkCandidate('https://files.pythonhosted.org/packages/66/64/3f60d8744752c9e4d6ace9ecd62875b2e5945cff878e123d5490264c5701/wmill-1.223.1-py3-none-any.whl (from https://pypi.org/simple/wmill/) (requires-python:>=3.7,<4.0)'))]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/scripts/compile.py", line 659, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### To reproduce

1. Create a flow with a python script
2. Fill this:

```python3
import wmill
# requirements:
# bilibili-api-python==16.1.1
# wmill==1.223.1
from bilibili_api import user, Credential

def main():
    return 111
```

### Expected behavior

Expect wmill to correctly install, since I need the client to set and get state.

### Browser information

Firefox latest

### Application version

CE v1.219.1-10-g583dae6a7

**Comment by JokerQyou** [comment]
By changing `import wmill` to `from wmill import get_state, set_state`, I can see the code editor is interpreting the types correctly without the explicit `wmill==1.223.1` requirement. But then the run would fail with `ModuleNotFoundError: No module named 'wmill'`

**Comment by rubenfiszel** [comment]
The latest version 1.224.0 has relaxed its requirement to > 0.24.0 so it should be enough to fix this
