### ISSUE TITLE
bug:  Uncaught (in promise) Error: Failed to generate lockfile. Status was: OK

### ISSUE THREAD

**Issue by sspencer-hubble** [windmill-labs/windmill#3174]
### Describe the bug

I'm trying to use Windmill with Python scripts.  I keep running into the following error.  The main issue with this error, beyond the fact that I think this is a bug is that the error message gives no useful information:

```
Generating metadata for f/common/test.py
Script f/common/test.py invalid, it cannot be parsed to infer schema.
error: Uncaught (in promise) Error: Failed to generate lockfile. Status was: OK
    throw new Error(
          ^
    at updateScriptLock (https://deno.land/x/wmill@v1.263.1/metadata.ts:217:11)
    at eventLoopTick (ext:core/01_core.js:64:7)
    at async generateMetadataInternal (https://deno.land/x/wmill@v1.263.1/metadata.ts:132:5)
    at async Command.generateMetadata [as actionHandler] (https://deno.land/x/wmill@v1.263.1/script.ts:618:5)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async https://deno.land/x/wmill@v1.263.1/main.ts:133:3
```

Once this occurs, the script.yaml files get created, but the lock sections are always blank, which means I cannot use any of my scripts because none of the dependencies get installed.  I have confirmed that pip is configured correctly in my environment.

### To reproduce

I don't really know.  I just use wmill for a bit and suddenly everything breaks when I call either `wmill script generate-metadata` or `wmill sync push`

### Expected behavior

At minimum wmill should provide a useful error message explaining why it cannot generate the lockfile.  Since all of my scripts are valid Python and pip is configured correctly I think there is also some sort of bug in play.

**Comment by rubenfiszel** [comment]
Hi @sspencer-hubble , what is the version of your remote?

**Comment by rubenfiszel** [comment]
also can you look at the corresponding Deps jobs (if any) on the runs page, then filter only Deps jobs in the Kind filter, to see if you can find any relevant logs there

**Comment by sspencer-hubble** [comment]
Here's a sample script:
```
import wmill


def test():
    try:
        api_key = wmill.get_variable("f/global/test_key")
    except wmill.VariableNotFoundError:
        raise Exception(
            'Please configure the "f/global/test_key" variable in the workspace.'
        )
```

And here's the Deps Log:

```
job 018d8466-f3a8-5eaa-4472-b4e82371562f on worker wk-default-953e59680f9b-70RNj (tag: python3)

resolving dependencies...
content of requirements:
wmill

  ERROR: Could not find a version that satisfies the requirement wmill (from versions: none)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('wmill')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('wmill'), parent=None)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/scripts/compile.py", line 659, in cli
    results = resolver.resolve(max_rounds=max_rounds)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/resolver.py", line 604, in resolve
    is_resolved = self._do_resolve(
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/piptools/resolver.py", line 636, in _do_resolve
    resolver.resolve(
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    raise error from e
pip._internal.exceptions.DistributionNotFound: No matching distribution found for wmill
```

**Comment by sspencer-hubble** [comment]
Upon further review, I believe this is user error due to us building or windmill worker container with pip config that expired.
