### ISSUE TITLE
bug:Python script - Lock file generation failed: ExitStatus(1)

### ISSUE THREAD

**Issue by denispol** [windmill-labs/windmill#3612]
### Describe the bug

I cannot manage to run the Python script that contains the below imports, although it's working locally. Whether run from a deployed flow, or as a script test individually as each Python script now always triggers ExecutionErr.

Here are the imports:

```python
import os
import wmill
import tempfile
from azure.storage.blob import BlobServiceClient
import psycopg2
import csv
```

The only import that works (if I strip each import one by one or try combinations), is wmill, alone. Adding other any import to the script results in ExecutionErr.

Here are logs of the error:

```
Windmill
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 585, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 71, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
```

### To reproduce

1. Create a Python script or a flow that contains a Python script
2. Import os, wmill, tempfile, azure.storage.blob, psycopg2 and csv, add boilerplate code that returns "Hello"
3. Execute
4. See the error

### Expected behavior

The imports should not create any issues as they are all compatible with Python 3.11 (tested locally)

### Screenshots

![image](https://github.com/windmill-labs/windmill/assets/19826856/9ed1eddd-41a6-4210-ac49-17cde3baebd7)

### Browser information

Firefox 125.0.2 (64-bit), Fedora 39

### Application version

windmill version (backend) CE v1.311.0

### Additional Context

I tried creating a new script, or a new flow, with the same code, and it results in the same error.

**Comment by rubenfiszel** [comment]
This is the real error which is above your logs:

```

    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [25 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/tmp/pip-resolve-urqfpjzh/azure_53e741e81f904c93a7e2555ed9b080ce/setup.py", line 60, in <module>
            raise RuntimeError(message)
        RuntimeError:
        
        Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore.
        Please install the service specific packages prefixed by `azure` needed for your application.
        
        The complete list of available packages can be found at:
        https://aka.ms/azsdk/python/all
        
        Here's a non-exhaustive list of common packages:
        
        -  azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc.
        -  azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts.
        -  azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM)
        -  azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault
        -  azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts
        
        A more comprehensive discussion of the rationale for this decision can be found in the following issue:
        https://github.com/Azure/azure-sdk-for-python/issues/10646
        
        
        [end of output]
```

I advice using extra_requirements: and then importing under main to make it work nicely:

```
import os
import wmill
import tempfile

import psycopg2
import csv

#extra_requirements:
#azure-storage-blob
def main:
  from azure.storage.blob import BlobServiceClient
```

**Comment by denispol** [comment]
It solved the issue, thanks!
