### ISSUE TITLE
bug: Undefined error with setup and signal 5

### ISSUE THREAD

**Issue by TheDan64** [windmill-labs/windmill#4311]
### Describe the bug

When setting up a new instance, and setting admin credentials I get the error in the UI:
```
There were an error with your setup:
undefined
```

In the worker node logs, I see:
```
Aug 31 14:36:46 windmill windmill-worker[5991]: 2024-08-31T14:36:46.954853Z  INFO worker: windmill-worker/src/worker.rs:1661: fetched job 0191a8dd-ffdf-75d0-fbca-2226067991b0, root job: none workspace_id=admins job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0 root_id=none worker=wk-default-3589f6959dc2-HpXyI hostname=3589f6959dc2
Aug 31 14:36:46 windmill windmill-worker[5991]: 2024-08-31T14:36:46.968166Z  INFO worker:job: windmill-worker/src/common.rs:576: wk-default-3589f6959dc2-HpXyI/0191a8dd-ffdf-75d0-fbca-2226067991b0 in admins worker memory snapshot 22060kB/9164kB worker=wk-default-3589f6959dc2-HpXyI hostname=3589f6959dc2 job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0
Aug 31 14:36:46 windmill windmill-worker[5991]: 2024-08-31T14:36:46.970850Z  INFO worker:job: windmill-worker/src/common.rs:595: wk-default-3589f6959dc2-HpXyI/0191a8dd-ffdf-75d0-fbca-2226067991b0 in admins still running.  mem: 896kB, peak mem: 896kB worker=wk-default-3589f6959dc2-HpXyI hostname=3589f6959dc2 job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0
Aug 31 14:36:47 windmill windmill-worker[5991]: 2024-08-31T14:36:47.055363Z  INFO worker:job: windmill-worker/src/common.rs:1166: child process 'deno run' took 92ms job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0 success=false mem_peak=896 worker=wk-default-3589f6959dc2-HpXyI worker=wk-default-3589f6959dc2-HpXyI hostname=3589f6959dc2 job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0
Aug 31 14:36:47 windmill windmill-worker[5991]: 2024-08-31T14:36:47.055433Z  INFO worker:job: windmill-worker/src/worker.rs:3175: finished Deno job 0191a8dd-ffdf-75d0-fbca-2226067991b0 workspace_id=admins is_ok=false worker=wk-default-3589f6959dc2-HpXyI hostname=3589f6959dc2 job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0
Aug 31 14:36:47 windmill windmill-worker[5991]: 2024-08-31T14:36:47.055490Z ERROR worker:completed_job: windmill-queue/src/jobs.rs:508: job 0191a8dd-ffdf-75d0-fbca-2226067991b0 did not succeed: {"error":{"message":"error during execution of the script:\nprocess terminated by signal: Some(\n    5,\n), stopped_signal: None, core_dumped: false","name":"ExecutionErr"}} worker=wk-default-3589f6959dc2-HpXyI hostname=3589f6959dc2 job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0
Aug 31 14:36:47 windmill windmill-worker[5991]: 2024-08-31T14:36:47.059695Z  INFO worker:completed_job: windmill-queue/src/jobs.rs:835: inserted completed job: 0191a8dd-ffdf-75d0-fbca-2226067991b0 (success: false) job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0 root_job="" path="g/all/setup_app/Change_Account" job_kind=Preview started_at="2024-08-31 14:36:46.952009 UTC" duration=104 permissioned_as="admin@windmill.dev" email="admin@windmill.dev" created_by="admin@windmill.dev" is_flow_step=false language=Some(Deno) success=false worker=wk-default-3589f6959dc2-HpXyI hostname=3589f6959dc2 job_id=0191a8dd-ffdf-75d0-fbca-2226067991b0
```

### To reproduce

1. Go to 'setup_app' page
2. Click on 'Set admin account and hub sync'
3. See error

### Expected behavior

Expected the button press to be successful

### Screenshots

![image](https://github.com/user-attachments/assets/dd564435-b9f3-4abc-a124-f0b70a81a506)

### Browser information

FF 129.0.2

### Application version

1.388.0

### Additional Context

May or may not be relevant, but I'm running the worker and server nodes in podman instances

**Comment by rubenfiszel** [comment]
Try with docker instead of podman. Signal 5 is SIGTRAP which is very strange here

**Comment by makkus** [comment]
Same error here, I'm using docker.

**Comment by amindadgar** [comment]
Same here on mac os. Any solutions?

the web console error
```
{
    "name": "ExecutionErr",
    "message": "ExitCode: 1, last log lines:\nDownload https://deno.land/x/windmill@v1.99.0/mod.ts\nerror: Import 'https://deno.land/x/windmill@v1.99.0/mod.ts' failed: error sending request for url (https://deno.land/x/windmill@v1.99.0/mod.ts): client error (Connect): tls handshake eof\n    at file:///tmp/windmill/wk-default-45ad3160c920-g38oU/019310da-dc4b-f8ae-c070-b267caf274ca/main.ts:1:24",
    "exit_code": 1
}
```


How to reproduce:
1. `open /Applications/Docker.app`
2. `curl https://raw.githubusercontent.com/windmill-labs/windmill/main/docker-compose.yml -o docker-compose.yml`
3. `curl https://raw.githubusercontent.com/windmill-labs/windmill/main/Caddyfile -o Caddyfile`
4. `curl https://raw.githubusercontent.com/windmill-labs/windmill/main/.env -o .env`
5. `docker compose up -d`
6. Login using `admin@windmill.dev` and password `changeme`
7. Change the base URL to `http://my_windmil` (also tried the default `http://localhost`)
8. Click on Save Setting button
9. Click on Finish Setup
10. Set any username and password
11. Click on the "Set admin account and hub sync" button

**Comment by waffelheld** [comment]
Had the same error. Solved it by editing the docker-compose.yml file and added the following env variables inside each environment config
      - HTTP_PROXY=http://your.proxy:port
      - HTTPS_PROXY=http://your.proxy:port
      - NO_PROXY=localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

**Comment by zvictor** [comment]
> Try with docker instead of podman. Signal 5 is SIGTRAP which is very strange here

Well, if I run with podman I get #5036.
If I run with docker I get into this one (#4311).

With docker it shows me the same `There were an error with your setup: undefined` dialog reported, but the dev console also shows:
```js
Object { name: "ExecutionErr", message: "ExitCode: 1, last log lines:\nDownload https://deno.land/x/windmill@v1.99.0/mod.ts\nerror: Import 'https://deno.land/x/windmill@v1.99.0/mod.ts' failed: error sending request for url (https://deno.land/x/windmill@v1.99.0/mod.ts): client error (Connect): dns error: failed to lookup address information: Temporary failure in name resolution: failed to lookup address information: Temporary failure in name resolution\n    at file:///tmp/windmill/wk-default-cec74cdaf12c-RRbID/01944a67-60f1-7a9d-7524-7acdad81748f/main.ts:1:24", exit_code: 1 }
AppPreview.4BTGsyV5.js:75:7700
```

It's not a network problem as I am able to open the deno file with no problems:
```
 curl -I https://deno.land/x/windmill@v1.99.0/mod.ts
HTTP/2 200 
accept-ranges: bytes
access-control-allow-origin: *
age: 13423107
x-frame-options: DENY
cache-control: public, max-age=31536000, immutable
content-length: 9174
content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
content-type: application/typescript; charset=utf-8
cross-origin-embedder-policy: same-origin
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
date: Wed, 07 Aug 2024 01:00:31 GMT
etag: "4be2bf23977e2d1d3fa7225bf9cbdba4"
last-modified: Wed, 10 May 2023 19:53:30 GMT
referrer-policy: strict-origin-when-cross-origin
server: deno/gcp-southamerica-east1
server-timing: fetchSource;dur=2
strict-transport-security: max-age=63072000; includeSubDomains; preload
vary: Origin
via: http/2 edgeproxy-h
x-amz-cf-id: H5ykH2rsNKDCDYtPKkDz38sJtDA5crxMRhw1nZfUwuL100BsVPfdVg==
x-amz-cf-pop: GRU3-P8
x-amz-replication-status: COMPLETED
x-amz-server-side-encryption: AES256
x-amz-version-id: 4HBTY3Pt_4n5Oph2gwZnKiiE0lrrUoeW
x-cache: Hit from cloudfront
x-content-type-options: nosniff
```

**Comment by zvictor** [comment]
Okay, I got it fixed when running on Docker (Podman is still broken).
The DNS resolution was[ broken inside Docker on my machine](https://github.com/NixOS/nixpkgs/issues/258141) and that was stopping Windmill from loading the file it needed.

**Comment by mdeville** [comment]
It also seems that this error message pops-up also when you use `admin@windmill.dev` as email address
