### ISSUE TITLE
bug: [python] unable to import wmill

### ISSUE THREAD

**Issue by mrl5** [windmill-labs/windmill#736]
### Describe the bug

usecase: `as a new windmill user I want to have python script example that I can successfully run`

job fails with this error
```console
The result keys are: error

Error during execution of the script:
Traceback (most recent call last):
  File "/tmp/main.py", line 6, in <module>
    inner_script = __import__("inner")
  File "/tmp/inner.py", line 2, in <module>
    import wmill
  File "/tmp/windmill/cache/pip_permanent/wmill==1.38.0/wmill/__init__.py", line 1, in <module>
    from .client import *
  File "/tmp/windmill/cache/pip_permanent/wmill==1.38.0/wmill/client.py", line 7, in <module>
    from windmill_api.client import AuthenticatedClient
```

I'm using default python script:
```python
import os
import wmill
from datetime import datetime

"""
Use Cmd/Ctrl + S to autoformat the code.
The client is used to interact with windmill itself through its standard API.
One can explore the methods available through autocompletion of `wmill.XXX`.
"""

def main(name: str = "Nicolas Bourbaki",
         age: int = 42,
         obj: dict = {"even": "dicts"},
         l: list = ["or", "lists!"],
         file_: bytes = bytes(0),
         dtime: datetime = datetime.now()):
    """A main function is required for the script to be able to accept arguments.
    Types are recommended."""
    print(f"Hello World and a warm welcome especially to {name}")
    print("and its acolytes..", age, obj, l, len(file_), dtime)
    # retrieve variables, including secrets by querying the windmill platform.
    # secret fetching is audited by windmill.
    secret = wmill.get_variable("g/all/pretty_secret")
    print(f"The env variable at `g/all/pretty_secret`: {secret}")
    # interact with the windmill platform to get the version
    version = wmill.get_version()
    # fetch reserved variables as environment variables
    user = os.environ.get("WM_USERNAME")
    # the return value is then parsed and can be retrieved by other scripts conveniently
    return {"version": version, "splitted": name.split(), "user": user}
```

### To reproduce

0. goto https://app.windmill.dev/
1. login to windmill
2. go to `/scripts` by clicking "Scripts" on menu
3. create new script by clicking "New script" in top left corner
4. choose "Python 3.10" in "Language" section
5. click "Test" button to trigger job preview
6. wait for error

### Expected behavior

all imports are resolved and script is executed successfully

### Application version
* https://app.windmill.dev/ state as of `2022-10-15T06:22:21+00:00`
* tested locally at commit 64014f17950f

### Additional Context

~~I suspect that this bug was introduced while implementing https://github.com/windmill-labs/windmill/issues/645~~
check https://github.com/windmill-labs/windmill/issues/736#issuecomment-1279675109

**Comment by mrl5** [comment]
looks like it's the issue with `wmill-1.38.0` itself

## steps to reproduce
```console
python3 -m venv ~/.virtualenvs/windmill
source .virtualenvs/windmill/bin/activate
pip install wmill
python3 -c 'import wmill'
```

## expected
`wmill` can be imported

## actual
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kuba/.virtualenvs/windmill/lib/python3.9/site-packages/wmill/__init__.py", line 1, in <module>
    from .client import *
  File "/home/kuba/.virtualenvs/windmill/lib/python3.9/site-packages/wmill/client.py", line 7, in <module>
    from windmill_api.client import AuthenticatedClient
ModuleNotFoundError: No module named 'windmill_api.client'
```

**Comment by mrl5** [comment]
tested again at `2022-10-15T06:56:52+00:00`:
* [x] on https://app.windmill.dev 
* [ ] by running steps to reproduce from https://github.com/windmill-labs/windmill/issues/736#issuecomment-1279675109

**so it's fixed from the https://app.windmill.dev perspective**

but I'm getting new error when reproducing https://github.com/windmill-labs/windmill/issues/736#issuecomment-1279675109

**Comment by mrl5** [comment]
this case is also passing now
* [ ] by running steps to reproduce from https://github.com/windmill-labs/windmill/issues/736#issuecomment-1279675109

but the requirement is to use python3.10 - this is a subject of https://github.com/windmill-labs/windmill/pull/738

closing this ticket now
